name: Build and Package

env:
  PKG_VERSION: ${{ github.ref }}
  Output: .\output

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v2.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core
      - uses: actions/setup-dotnet@v1.4.0

      - name: Build
      - run: dotnet build '.\src\Mw.UmbForms.Rte.sln' --configuration Release
        
      - name: install Umbraco Package
      - run: dotnet tool install Umbraco.Tools.Packages
      
  package:
    needs: build
    runs-on: windows-latest
    steps:

      - name: Pack Umbraco package
      - run: umbpack pack .\src\package.xml -o ${{env.Output}} -v ${{ env.PKG_VERSION }} 

      - name: Pack NuGet package
        run: dotnet pack ./src/ 
              --configuration Release
              --output ${{env.Output}}
              -p:Version=${{ env.PKG_VERSION }} 
              -p:PackageId=Umbraco.Tools.Packages
