name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        
      - name: Build
      - uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.100' # SDK Version to use
      - run: dotnet build '.\src\Mw.UmbForms.Rte.sln' --configuration Release
        
      - name: install Umbraco Package
      - run: dotnet tool install Umbraco.Tools.Packages
      
      - name: Package
      - run: umbpack pack '.\src\package.xml' -o output -v ${{github.ref}}
